# Generated by Django 5.1.1 on 2024-09-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
        migrations.AddField(
            model_name='vote',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'На модерации'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена')], default='pending', max_length=20),
        ),
    ]
