# Generated by Django 5.1.3 on 2024-11-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
