# Generated by Django 5.1.3 on 2024-11-20 18:36

import utils.file_uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='defaultuser.png', upload_to=utils.file_uploader.uploaded_file_path),
        ),
    ]
